// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbQHymJkakiKyfYHYHmf9D7e_818SVVc',
    appId: '1:752938708459:web:7afe66d7c91de32b30bdae',
    messagingSenderId: '752938708459',
    projectId: 'dmd-project-7d5bc',
    authDomain: 'dmd-project-7d5bc.firebaseapp.com',
    storageBucket: 'dmd-project-7d5bc.firebasestorage.app',
    measurementId: 'G-WWK6WT7TPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYpI9c4TN25wFc0zCcD2V8Jrz7lbAvx2k',
    appId: '1:752938708459:android:ca472d83d15e442630bdae',
    messagingSenderId: '752938708459',
    projectId: 'dmd-project-7d5bc',
    storageBucket: 'dmd-project-7d5bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-NdyL1X65qlUUqaqrygM7z__AS83SQLM',
    appId: '1:752938708459:ios:247447225555cdce30bdae',
    messagingSenderId: '752938708459',
    projectId: 'dmd-project-7d5bc',
    storageBucket: 'dmd-project-7d5bc.firebasestorage.app',
    iosBundleId: 'com.example.mgtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-NdyL1X65qlUUqaqrygM7z__AS83SQLM',
    appId: '1:752938708459:ios:247447225555cdce30bdae',
    messagingSenderId: '752938708459',
    projectId: 'dmd-project-7d5bc',
    storageBucket: 'dmd-project-7d5bc.firebasestorage.app',
    iosBundleId: 'com.example.mgtApp',
  );
}
